const fs = require('fs');
const path = require('path');
const {
  User,
  MembershipApplication,
  Contribution,
  ContributionIncreaseRequest,
  Loan,
  LoanRepayment,
  Expense,
  ProfitShare,
  Notification,
  AuditNote,
  Settings,
  LayyahApplication,
  AnimalAcquisitionRequest,
  LoanAgreement,
  ContributionWithdrawal,
  BroadcastMessage,
  Complaint,
  DirectMessage,
  EducationalDocument,
  LoanLiquidation,
  ActivityLog,
  SystemBackup,
  sequelize
} = require('../models');

const BACKUPS_DIR = path.join(__dirname, '..', 'backups');

// Ensure backups directory exists
const ensureBackupDir = () => {
  if (!fs.existsSync(BACKUPS_DIR)) {
    fs.mkdirSync(BACKUPS_DIR, { recursive: true });
  }
  return BACKUPS_DIR;
};

// Ensure system_backups table exists in database
let tableSynced = false;
const ensureBackupTable = async () => {
  if (tableSynced) return;
  try {
    await SystemBackup.sync({ alter: true });
    tableSynced = true;
  } catch (err) {
    try {
      await sequelize.query(`
        CREATE TABLE IF NOT EXISTS system_backups (
          id SERIAL PRIMARY KEY,
          filename VARCHAR(255) NOT NULL,
          filepath VARCHAR(500) NOT NULL,
          format VARCHAR(20) NOT NULL DEFAULT 'json',
          file_size BIGINT NOT NULL DEFAULT 0,
          total_records INTEGER NOT NULL DEFAULT 0,
          table_counts JSONB,
          status VARCHAR(30) NOT NULL DEFAULT 'completed',
          error_message TEXT,
          notes TEXT,
          created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
      `);
      tableSynced = true;
    } catch (rawErr) {
      console.warn('ensureBackupTable warning:', rawErr.message);
    }
  }
};

// Define all models and sanitization rules
const getModelsConfig = () => [
  { key: 'settings', label: 'Settings', model: Settings },
  { key: 'membership_applications', label: 'Membership Applications', model: MembershipApplication },
  {
    key: 'users',
    label: 'Users',
    model: User,
    sanitize: (rows) => rows.map(u => {
      const copy = { ...u };
      delete copy.password_hash;
      delete copy.reset_password_token;
      delete copy.reset_password_expires;
      return copy;
    })
  },
  { key: 'contributions', label: 'Contributions', model: Contribution },
  { key: 'contribution_increase_requests', label: 'Contribution Increase Requests', model: ContributionIncreaseRequest },
  { key: 'loans', label: 'Loans', model: Loan },
  { key: 'loan_repayments', label: 'Loan Repayments', model: LoanRepayment },
  { key: 'loan_liquidations', label: 'Loan Liquidations', model: LoanLiquidation },
  { key: 'loan_agreements', label: 'Loan Agreements', model: LoanAgreement },
  { key: 'expenses', label: 'Expenses', model: Expense },
  { key: 'profit_shares', label: 'Profit Shares', model: ProfitShare },
  { key: 'contribution_withdrawals', label: 'Contribution Withdrawals', model: ContributionWithdrawal },
  { key: 'layyah_applications', label: 'Layyah Applications', model: LayyahApplication },
  { key: 'animal_acquisition_requests', label: 'Animal Acquisition Requests', model: AnimalAcquisitionRequest },
  { key: 'complaints', label: 'Complaints', model: Complaint },
  { key: 'activity_logs', label: 'Activity Logs', model: ActivityLog },
  { key: 'audit_notes', label: 'Audit Notes', model: AuditNote },
  { key: 'notifications', label: 'Notifications', model: Notification },
  { key: 'broadcast_messages', label: 'Broadcast Messages', model: BroadcastMessage },
  { key: 'direct_messages', label: 'Direct Messages', model: DirectMessage },
  { key: 'educational_documents', label: 'Educational Documents', model: EducationalDocument }
];

// SQL escape helper
const escapeSqlValue = (val) => {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return Number.isFinite(val) ? val.toString() : 'NULL';
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
  if (val instanceof Date) return `'${val.toISOString()}'`;
  if (typeof val === 'object') {
    return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
  }
  return `'${String(val).replace(/'/g, "''")}'`;
};

// Generate SQL Insert script
const generateSqlScript = (tablesData, generatedAt, creatorName) => {
  let sql = `-- ========================================================\n`;
  sql += `-- IMAN Multi-Purpose Cooperative Society Database Dump\n`;
  sql += `-- Generated At: ${generatedAt}\n`;
  sql += `-- Generated By: ${creatorName || 'System Admin'}\n`;
  sql += `-- ========================================================\n\n`;
  sql += `BEGIN;\n\n`;

  for (const [tableKey, rows] of Object.entries(tablesData)) {
    sql += `-- --------------------------------------------------------\n`;
    sql += `-- Table: ${tableKey} (${rows.length} records)\n`;
    sql += `-- --------------------------------------------------------\n`;

    if (rows.length === 0) {
      sql += `-- No records for ${tableKey}\n\n`;
      continue;
    }

    const columns = Object.keys(rows[0]);
    const colList = columns.map(c => `"${c}"`).join(', ');

    for (const row of rows) {
      const values = columns.map(col => escapeSqlValue(row[col])).join(', ');
      sql += `INSERT INTO "${tableKey}" (${colList}) VALUES (${values});\n`;
    }
    sql += `\n`;
  }

  sql += `COMMIT;\n`;
  return sql;
};

// Convert array of objects to CSV string
const convertToCsv = (rows) => {
  if (!rows || rows.length === 0) return '';
  const headers = Object.keys(rows[0]);
  
  const headerRow = headers.map(h => `"${String(h).replace(/"/g, '""')}"`).join(',');
  const dataRows = rows.map(row => {
    return headers.map(col => {
      let val = row[col];
      if (val === null || val === undefined) return '""';
      if (val instanceof Date) val = val.toISOString();
      else if (typeof val === 'object') val = JSON.stringify(val);
      return `"${String(val).replace(/"/g, '""')}"`;
    }).join(',');
  });

  return [headerRow, ...dataRows].join('\r\n');
};

class BackupService {
  /**
   * Create a full database backup in JSON or SQL format
   */
  async createFullBackup({ format = 'json', notes = '', user }) {
    await ensureBackupTable();
    ensureBackupDir();
    const cleanFormat = format.toLowerCase() === 'sql' ? 'sql' : 'json';
    const timestampStr = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `iman_backup_${cleanFormat}_${timestampStr}.${cleanFormat}`;
    const filepath = path.join(BACKUPS_DIR, filename);

    const modelsConfig = getModelsConfig();
    const tablesData = {};
    const tableCounts = {};
    let totalRecords = 0;

    // Collect data from each model
    for (const item of modelsConfig) {
      try {
        let rows = await item.model.findAll({ raw: true });
        if (typeof item.sanitize === 'function') {
          rows = item.sanitize(rows);
        }
        tablesData[item.key] = rows;
        tableCounts[item.key] = rows.length;
        totalRecords += rows.length;
      } catch (err) {
        console.warn(`Warning: failed to query table ${item.key} for backup:`, err.message);
        tablesData[item.key] = [];
        tableCounts[item.key] = 0;
      }
    }

    const generatedAt = new Date().toISOString();
    const creatorName = user?.name || user?.membershipApplication?.name || `Admin #${user?.id || '0'}`;

    if (cleanFormat === 'json') {
      const backupPayload = {
        system: 'IMAN Multi-Purpose Cooperative Society Management System',
        version: '1.0.0',
        backup_type: 'full',
        format: 'json',
        generated_at: generatedAt,
        generated_by: {
          id: user?.id,
          name: creatorName,
          role: user?.role,
          email: user?.email
        },
        summary: {
          total_tables: Object.keys(tablesData).length,
          total_records: totalRecords,
          table_counts: tableCounts
        },
        data: tablesData
      };

      fs.writeFileSync(filepath, JSON.stringify(backupPayload, null, 2), 'utf8');
    } else {
      const sqlContent = generateSqlScript(tablesData, generatedAt, creatorName);
      fs.writeFileSync(filepath, sqlContent, 'utf8');
    }

    const stats = fs.statSync(filepath);
    const fileSize = stats.size;

    // Save record in database
    const backupRecord = await SystemBackup.create({
      filename,
      filepath,
      format: cleanFormat,
      file_size: fileSize,
      total_records: totalRecords,
      table_counts: tableCounts,
      status: 'completed',
      notes: notes || `Full ${cleanFormat.toUpperCase()} database backup`,
      created_by: user?.id || null,
      created_at: new Date()
    });

    // Log Activity
    try {
      await ActivityLog.create({
        user_id: user?.id || 1,
        action: 'admin_create_backup',
        resource_type: 'system_backup',
        resource_id: backupRecord.id,
        description: `Admin created ${cleanFormat.toUpperCase()} system backup (${totalRecords} records, ${(fileSize / 1024).toFixed(1)} KB)`,
        metadata: {
          filename,
          format: cleanFormat,
          file_size: fileSize,
          total_records: totalRecords
        }
      });
    } catch (logErr) {
      console.error('Failed to log backup activity:', logErr);
    }

    return backupRecord;
  }

  /**
   * Get all backups with pagination
   */
  async listBackups({ page = 1, limit = 20 } = {}) {
    await ensureBackupTable();
    const offset = (page - 1) * limit;
    const { count, rows } = await SystemBackup.findAndCountAll({
      order: [['created_at', 'DESC']],
      limit: parseInt(limit),
      offset: parseInt(offset),
      include: [
        {
          model: User,
          as: 'creator',
          attributes: ['id', 'role', 'status'],
          include: [
            {
              model: MembershipApplication,
              as: 'membershipApplication',
              attributes: ['name', 'psn', 'email']
            }
          ]
        }
      ]
    });

    return {
      backups: rows,
      pagination: {
        total: count,
        page: parseInt(page),
        limit: parseInt(limit),
        totalPages: Math.ceil(count / limit)
      }
    };
  }

  /**
   * Get overview stats
   */
  async getBackupStats() {
    await ensureBackupTable();
    const totalBackups = await SystemBackup.count({ where: { status: 'completed' } });
    const latestBackup = await SystemBackup.findOne({
      where: { status: 'completed' },
      order: [['created_at', 'DESC']]
    });

    const totalBytes = (await SystemBackup.sum('file_size', { where: { status: 'completed' } })) || 0;

    // Approximate live records across main tables
    let liveRecords = 0;
    try {
      const [u, c, l, e, w, ly] = await Promise.all([
        User.count(),
        Contribution.count(),
        Loan.count(),
        Expense.count(),
        ContributionWithdrawal.count(),
        LayyahApplication.count()
      ]);
      liveRecords = u + c + l + e + w + ly;
    } catch (e) {
      liveRecords = 0;
    }

    return {
      total_backups: totalBackups,
      latest_backup: latestBackup,
      total_storage_bytes: parseInt(totalBytes),
      total_live_records: liveRecords,
      supported_tables: getModelsConfig().length
    };
  }

  /**
   * Get backup by ID for download
   */
  async getBackupById(id) {
    await ensureBackupTable();
    const backup = await SystemBackup.findByPk(id);
    if (!backup) return null;
    return backup;
  }

  /**
   * Delete a backup file and its record
   */
  async deleteBackup(id, user) {
    await ensureBackupTable();
    const backup = await SystemBackup.findByPk(id);
    if (!backup) return false;

    // Delete file if exists
    try {
      if (fs.existsSync(backup.filepath)) {
        fs.unlinkSync(backup.filepath);
      }
    } catch (e) {
      console.warn(`Could not delete file ${backup.filepath}:`, e.message);
    }

    await backup.destroy();

    // Log Activity
    try {
      await ActivityLog.create({
        user_id: user?.id || 1,
        action: 'admin_delete_backup',
        resource_type: 'system_backup',
        resource_id: id,
        description: `Admin deleted backup ${backup.filename}`,
        metadata: { filename: backup.filename }
      });
    } catch (logErr) {
      console.error('Failed to log delete backup activity:', logErr);
    }

    return true;
  }

  /**
   * Export specific module to CSV
   */
  async exportModuleCsv(moduleKey) {
    const key = (moduleKey || '').toLowerCase();
    const configMap = {
      members: {
        model: MembershipApplication,
        filename: `members_export_${Date.now()}.csv`
      },
      users: {
        model: User,
        sanitize: (rows) => rows.map(u => {
          const copy = { ...u };
          delete copy.password_hash;
          delete copy.reset_password_token;
          delete copy.reset_password_expires;
          return copy;
        }),
        filename: `users_export_${Date.now()}.csv`
      },
      contributions: {
        model: Contribution,
        filename: `contributions_export_${Date.now()}.csv`
      },
      loans: {
        model: Loan,
        filename: `loans_export_${Date.now()}.csv`
      },
      loan_repayments: {
        model: LoanRepayment,
        filename: `loan_repayments_export_${Date.now()}.csv`
      },
      expenses: {
        model: Expense,
        filename: `expenses_export_${Date.now()}.csv`
      },
      withdrawals: {
        model: ContributionWithdrawal,
        filename: `withdrawals_export_${Date.now()}.csv`
      },
      layyah: {
        model: LayyahApplication,
        filename: `layyah_export_${Date.now()}.csv`
      },
      profit_shares: {
        model: ProfitShare,
        filename: `profit_shares_export_${Date.now()}.csv`
      },
      activity_logs: {
        model: ActivityLog,
        filename: `activity_logs_export_${Date.now()}.csv`
      },
      settings: {
        model: Settings,
        filename: `settings_export_${Date.now()}.csv`
      }
    };

    const target = configMap[key];
    if (!target) {
      throw new Error(`Unsupported module: ${moduleKey}`);
    }

    let rows = await target.model.findAll({ raw: true });
    if (typeof target.sanitize === 'function') {
      rows = target.sanitize(rows);
    }

    const csvContent = convertToCsv(rows);
    return {
      filename: target.filename,
      csvContent,
      count: rows.length
    };
  }
}

module.exports = new BackupService();
