import React, { createContext, useContext, useEffect, useState } from 'react';
import axios from 'axios';
import { API_URL } from '../config';

interface TenantTheme {
  primaryColor?: string;
  secondaryColor?: string;
  logoUrl?: string;
  landingPage?: {
    heroTitle?: string;
    heroSubtitle?: string;
    aboutText?: string;
    contactEmail?: string;
    contactPhone?: string;
  };
}

interface TenantConfig {
  id: string;
  name?: string;
  cooperative_type: 'islamic' | 'conventional';
  theme: TenantTheme;
  features: Record<string, boolean>;
}

interface TenantContextValue {
  tenant: TenantConfig | null;
  isLoading: boolean;
  error: string | null;
  hasFeature: (featureName: string) => boolean;
}

const TenantContext = createContext<TenantContextValue>({
  tenant: null,
  isLoading: true,
  error: null,
  hasFeature: () => true,
});

// ── Color Palette Generation Utilities ──────────────────────────────────

/** Parse a hex color string into an {r, g, b} object (0-255). */
const hexToRgb = (hex: string) => {
  hex = hex.replace(/^#/, '');
  if (hex.length === 3) hex = hex.split('').map(x => x + x).join('');
  return {
    r: parseInt(hex.substring(0, 2), 16),
    g: parseInt(hex.substring(2, 4), 16),
    b: parseInt(hex.substring(4, 6), 16),
  };
};

/** Convert an {r, g, b} (0-255) tuple to an HSL string: "H S% L%" */
const rgbToHslString = (r: number, g: number, b: number): string => {
  r /= 255; g /= 255; b /= 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      case b: h = (r - g) / d + 4; break;
    }
    h /= 6;
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
};

/** Mix two RGB colors by a ratio (0 = all c1, 1 = all c2). */
const mixRgb = (c1: {r:number;g:number;b:number}, c2: {r:number;g:number;b:number}, ratio: number) => ({
  r: Math.round(c1.r + (c2.r - c1.r) * ratio),
  g: Math.round(c1.g + (c2.g - c1.g) * ratio),
  b: Math.round(c1.b + (c2.b - c1.b) * ratio),
});

/**
 * Generate a full 10-step Tailwind-style color palette from a single hex color.
 * Returns an object { '50': 'H S% L%', '100': '…', … '900': '…' }
 *
 * Strategy:
 *  - The input color becomes shade 500 (the anchor).
 *  - Shades 50–400 are generated by mixing the base with white at decreasing intensity.
 *  - Shades 600–900 are generated by mixing the base with black at increasing intensity.
 */
const generatePalette = (hex: string): Record<string, string> => {
  const base = hexToRgb(hex);
  const white = { r: 255, g: 255, b: 255 };
  const black = { r: 0, g: 0, b: 0 };

  // Tint ratios (toward white) for shades lighter than 500
  const tints: [string, number][] = [
    ['50',  0.95],
    ['100', 0.88],
    ['200', 0.75],
    ['300', 0.55],
    ['400', 0.30],
  ];

  // Shade ratios (toward black) for shades darker than 500
  const shades: [string, number][] = [
    ['600', 0.15],
    ['700', 0.30],
    ['800', 0.45],
    ['900', 0.60],
  ];

  const palette: Record<string, string> = {};
  for (const [name, ratio] of tints) {
    const c = mixRgb(base, white, ratio);
    palette[name] = rgbToHslString(c.r, c.g, c.b);
  }
  palette['500'] = rgbToHslString(base.r, base.g, base.b);
  for (const [name, ratio] of shades) {
    const c = mixRgb(base, black, ratio);
    palette[name] = rgbToHslString(c.r, c.g, c.b);
  }
  return palette;
};

/**
 * Apply the full generated palette to the document root as CSS custom properties.
 * Also sets the base --primary variable used by shadcn-style components.
 */
const applyThemePalette = (hex: string) => {
  const palette = generatePalette(hex);
  const root = document.documentElement;

  for (const [shade, hsl] of Object.entries(palette)) {
    root.style.setProperty(`--primary-${shade}`, hsl);
  }
  // Set the base --primary (used by shadcn DEFAULT) to match shade 600
  root.style.setProperty('--primary', palette['600']);
  // Set --ring to match the primary for focus-ring consistency
  root.style.setProperty('--ring', palette['500']);
};

export const TenantProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [tenant, setTenant] = useState<TenantConfig | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchTenantConfig = async () => {
      try {
        const apiUrl = API_URL || 'http://localhost:3001';
        
        // Check URL for tenant query param to support local preview
        const urlParams = new URLSearchParams(window.location.search);
        const tenantParam = urlParams.get('tenant');
        
        const headers: Record<string, string> = {};
        if (tenantParam) {
          headers['x-tenant-id'] = tenantParam;
          localStorage.setItem('previewTenantId', tenantParam);
        } else {
          const storedTenantId = localStorage.getItem('previewTenantId');
          if (storedTenantId) {
            headers['x-tenant-id'] = storedTenantId;
          }
        }

        const response = await axios.get(`${apiUrl}/tenant/config`, { 
          withCredentials: true,
          headers
        });
        
        if (response.data.success && response.data.data) {
          const config = response.data.data;
          setTenant(config);

          // Apply full primary color palette to the document
          if (config.theme?.primaryColor) {
            applyThemePalette(config.theme.primaryColor);
          }
          // Apply secondary color if provided
          if (config.theme?.secondaryColor) {
            const sec = hexToRgb(config.theme.secondaryColor);
            document.documentElement.style.setProperty('--secondary', rgbToHslString(sec.r, sec.g, sec.b));
          }
        } else {
          setError('Failed to load tenant configuration');
        }
      } catch (err: any) {
        console.error('Error fetching tenant config:', err);
        setError(err.message || 'Error fetching tenant config');
      } finally {
        setIsLoading(false);
      }
    };

    fetchTenantConfig();
  }, []);

  const hasFeature = (featureName: string) => {
    if (!tenant || !tenant.features) return true; // Default to true if not configured
    return tenant.features[featureName] !== false; // Only disable if explicitly false
  };

  return (
    <TenantContext.Provider value={{ tenant, isLoading, error, hasFeature }}>
      {/* 
        You might want to show a loading screen while fetching tenant config,
        so the app doesn't render with default colors and then flash to tenant colors.
      */}
      {isLoading ? (
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary-600"></div>
        </div>
      ) : (
        children
      )}
    </TenantContext.Provider>
  );
};

export const useTenant = () => useContext(TenantContext);
