ALTER TABLE direct_messages
  ADD COLUMN IF NOT EXISTS attachment_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS attachment_mime VARCHAR(100),
  ADD COLUMN IF NOT EXISTS attachment_size INTEGER;

